version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 9000:80
    depends_on:
       - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bite
      MYSQL_USER: bite
      MYSQL_PASSWORD: password
    ports:
      - 13306:3306
    volumes:
      - myvolume:/var/lib/mysql



volumes:
  myvolume: