# Generated by Django 4.2.2 on 2023-07-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.IntegerField()),
                ("contact_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_id", models.IntegerField()),
                ("contact_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PhoneStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedId", models.IntegerField(null=True)),
                (
                    "linkPrecedence",
                    models.CharField(
                        choices=[("primary", "primary"), ("secondary", "secondary")],
                        max_length=20,
                    ),
                ),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
                ("deletedAt", models.DateTimeField(null=True)),
                (
                    "email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.emailstore",
                    ),
                ),
                (
                    "phoneNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.phonestore",
                    ),
                ),
            ],
        ),
    ]
