# Generated by Django 4.2.2 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
        migrations.AlterField(
            model_name="contact",
            name="updatedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
